const phrases = [
  "A mí me gustan las cuentas claras y el chocolate espeso",
  "Uno no es monedita de oro para caerle bien a todo el mundo",
  "Píntemela a ver y yo le digo cuántos pares son tres moscas",
  "Ni que estuviéramos bravos",
  "¿Durmió conmigo anoche o qué, que no saluda?",
  "Esos dos son uña y mugre",
  "Me la puso de pa´rriba",
  "Que se va de playa, ¿no?",
  "Sóbese que no hay pomada",
  "Tengo un filo, que si me agacho me corto",
  "Está que se las pica.",
  "¿Qué desea de principio? ¿Garbanzo u arveja?",
  "¡Quite d'iai!",
  "Bueno se me van bajando del bus aquí todos",
  "¿Y eso quién pidió pollo?",
  "¿Qué hay pa´hacer? Pues, empanadas que es lo quemás se vende.",
  "¡Ay, no se me coloque así!",
  "¡Nanay cucas!",
  "Esto está más largo que una semana sin carne",
  "Váyase por la sombrita",
  "¡Lo visto pero no lo mantengo!",
  "¡qué chucha tan cebollera!",
  "¡Se ve que se toma la sopita!",
  "¿Cómo está? Regular, tres cuartos...",
  "qué huesera!",
  "qué pitos toca esa vaina ahí?",
  "Me sale lo comido por lo servido",
  "¡ahí nos vidrios las caratulas!",
  "Ese man baila como un trompo",
  "Lo que le diga es mentira",
  "¡Sale pa´pintura (o pa´la foto)!",
  "¡Tan chistoso! ¿Fue que tomó caldo de payasito?",
  "uy sizas parce!",
  "¡Uuuuyyyyyyyy, se nos creció el enano!",
  "¡Déle chancleta!",
  "¡Hmmm, ese huevito quiere sal!",
  "Se orinaron de la risa...",
  "No me abra los ojos que no le voy a echar gotas",
  "No me levante las cejas que no voy a pasar por debajo.",
  "¡Dichosos los ojos!",
  "Vecino nos lleva por 500?",
  "quién llamo tintos??o quién pidió taxi?",
  "pailas mijo(a)!",
  "¡Chaos!",
  "¡Qué hubos!",
  "Mi'hace el favor y le baja al tonito.",
  "Aquí en la lucha, bregando como negro.",
  "¡Hay que estar mosca, papá!",
  "Pa'qué, pero ese man tiene madera",
  "Esa vieja está mas arreglada que muchacha de servicio en domingo.",
  "Lo tengo entre ojos",
  "¿Usted qué come, que adivina?",
  "¡Usted si mata un marrano a cantaleta! ¿No?",
  "Mugre que no mata, engorda.",
  "pa´las q sea papá!",
  "¡Ese man es mas picado que muela de gamin!",
  "¡Oiga, sardino! ¿Qué se dice?",
  "¡Ese man sí tiene suin (swing)!",
  "¡Tengo un filin (feeling)!",
  "¡vieja la cédula!",
  "El que tiene tienda, que la atienda.",
  "Aquí no se trabaja pero se goza...",
  "Usted está MFT (miando fuera del tiesto);",
  "¡Hum, ya dijo!",
  "No me alegro, pero sí me da un fresquito...",
  "¡Ese man está qu'echa chispas!",
  "La tecnología me atropella.",
  "Tengo una miada que me sabe la boca a champaña.",
  "Esa vieja es más fea que un carro por debajo",
  "Tiene más patas que un chance.",
  "Muy bonito no?",
  "A esta vaina no le cabe un tinto (enTransMilenio).",
  "Siga siga que hay espacio atras, se me acomoda por el pasillo por favor.",
  "¡Tocó almorzar corrientazo!",
  "A ese man lo dejaron mirando viendo un chispero.",
  "Esa vieja sí que es guapachosa.",
  "El viejito esta capando cementerio.",
  "¿Cómo se llama tu nombre? ¿Dónde vive tudirección?",
  "Señor taxista, lléveme al centro, pero pilas con el muñeco en el taximetro.",
  "Señoras y señores con el permiso del señor conductor, les vengo ofreciendo la promoción de la rica y deliciosa fruna. Una en doscientos y tres en quinientos. Para mayor economía, lleve seis en mil. El producido de esta venta es para pagar el arriendo, ayudar en la comidita de la casa y el colegio de mis otros 8 hermanitos.",
  "Sumercé, ¿se le ofrece algo?",
  "cómo no moñito!",
  "Tome pa'la gaseosa (propina)",
  "Mono, ¿le limpio el vidrio?",
  "Chilla más que marrano alzado.",
  "La cucha y el catano.",
  "No se apene, sin verguenza, estamos en confianza!",
  "Esta respirando por la herida.",
  "El que come solo muere solo y atorado.",
  "Vecina, ¿la ñapa? (vendaje, encime, etc.)",
  "Juemadre, juemichica, juepucha, y todos los juez que usted ha escuchado",
  "Mas puntual que novia fea.",
  "Jincho pero contento.",
  "Me eché un motoso.",
  "come mas que plata al 20%.",
  "Se rumbiaron a la hija de ese man.",
  "Le llenaron la barriga de huesitos por andar de patisuelta",
  "Indio patirrajao",
  "Déle forguar a este imeil pa que lo lean en el ciberespacio",
  "¡Uich, qué boleta!o qué oso!o qué bandera!",
];

const colombianPrase = (log = false) => {
  const message = phrases[Math.floor(Math.random() * phrases.length)];
  if (log) console.log(`\x1b[34m${message}\x1b[89m`);
  return message;
};

module.exports = {
  colombianPrase,
};
